name: Github Action
on: [push, pull_request]
jobs:
  Compile_ts_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: yarn install
        run: yarn install
      - run: npm install -g typescript
      - name: tsc
        uses: icrawl/action-tsc@v1